# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fair', models.IntegerField()),
                ('eco', models.IntegerField()),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.AlterModelTable(
            name='concerns',
            table='Concerns',
        ),
        migrations.AddField(
            model_name='company',
            name='concern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Concerns'),
        ),
    ]
