# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170419_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fair', models.IntegerField()),
                ('eco', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Company')),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
    ]
