# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ean', models.IntegerField(verbose_name=17)),
                ('fair', models.IntegerField()),
                ('eco', models.IntegerField()),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Concerns')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
