# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20170419_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='concern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Concerns'),
        ),
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Companies'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Companies'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='concern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Concerns'),
        ),
        migrations.AlterField(
            model_name='products',
            name='concern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Concerns'),
        ),
    ]
