# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_brands_altname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
