# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20170501_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='urlZumHersteller',
            new_name='url',
        ),
        migrations.AddField(
            model_name='brands',
            name='img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
