# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20170501_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerns',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
