# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_concerns_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='newConcernsByUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fair', models.IntegerField()),
                ('eco', models.IntegerField()),
                ('url', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'newConcernsByUsers',
            },
        ),
    ]
