# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_newconcernsbyusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concerns',
            new_name='Concern',
        ),
        migrations.RenameModel(
            old_name='newConcernsByUsers',
            new_name='newConcernByUsers',
        ),
        migrations.AlterModelTable(
            name='concern',
            table='Concern',
        ),
        migrations.AlterModelTable(
            name='newconcernbyusers',
            table='newConcernByUsers',
        ),
    ]
