# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20170524_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='newconcernbyusers',
            name='counter',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
