# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20170524_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newProductByUsers',
            new_name='New_Brand_by_Users',
        ),
        migrations.RenameModel(
            old_name='newConcernByUsers',
            new_name='New_Company_by_Users',
        ),
        migrations.RenameModel(
            old_name='newBrandByUsers',
            new_name='New_Concern_by_Users',
        ),
        migrations.RenameModel(
            old_name='newCompanyByUsers',
            new_name='New_Product_by_Users',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='new_brand_by_users',
            table='newBrandByUsers',
        ),
        migrations.AlterModelTable(
            name='new_company_by_users',
            table='newCompanyByUsers',
        ),
        migrations.AlterModelTable(
            name='new_concern_by_users',
            table='newConcernByUsers',
        ),
        migrations.AlterModelTable(
            name='new_product_by_users',
            table='newProductByUsers',
        ),
    ]
