# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20170525_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='n.a.', max_length=50, null=True),
        ),
    ]
